environment:
  matrix:
    - COMPILER: mingw-w64
      PCAP_URL: https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
      PCAP_FILE: WpdPack_4_1_2.zip
      PCAP_EXTRACT: c:\
      PCAP_PATH: "c:\\WpdPack\\Lib\\x64;c:\\WinDivert-1.4.3-A\\x86_64"
      CONFIGURE: "--with-libpcap-libraries=/c/WpdPack/Lib/x64 --with-libpcap-includes=/c/WpdPack/Include --enable-windivert --with-windivert-include=/c/WinDivert-1.4.3-A/include --with-windivert-libraries=/c/WinDivert-1.4.3-A/x86_64 --enable-unittests"
      MINGW_DIR: c:\msys64\mingw64
      MINGW_ARCH: x86_64
      RUST: enable
      WINDIVERT: enable
      UNITTESTS: enable
      CFLAGS: -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function

    - COMPILER: mingw
      PCAP_URL: https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
      PCAP_FILE: WpdPack_4_1_2.zip
      PCAP_EXTRACT: c:\
      PCAP_PATH: "c:\\WpdPack\\Lib"
      CONFIGURE: "--with-libpcap-libraries=/c/WpdPack/Lib --with-libpcap-includes=/c/WpdPack/Include"
      MINGW_DIR: c:\msys64\mingw32
      MINGW_ARCH: i686
      RUST: enable
      WINDIVERT: disable
      UNITTESTS: disable
      CFLAGS: -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function

    - COMPILER: mingw-w64
      PCAP_URL: https://nmap.org/npcap/dist/npcap-sdk-1.01.zip
      PCAP_FILE: npcap-sdk-1.01.zip
      PCAP_EXTRACT: c:\npcap\
      PCAP_PATH: "c:\\npcap\\Lib\\x64"
      CONFIGURE: "--with-libpcap-libraries=/c/npcap/Lib/x64 --with-libpcap-includes=/c/npcap/Include"
      MINGW_DIR: c:\msys64\mingw64
      MINGW_ARCH: x86_64
      RUST: enable
      WINDIVERT: disable
      UNITTESTS: disable
      CFLAGS: -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-function

before_build:
  - set Path=%MINGW_DIR%\bin;%Path%
  - c:\msys64\usr\bin\pacman -Su --noconfirm libyaml-devel pcre-devel jansson-devel
  - c:\msys64\usr\bin\pacman -Su --noconfirm mingw-w64-"%MINGW_ARCH%"-libyaml
  - c:\msys64\usr\bin\pacman -Su --noconfirm mingw-w64-"%MINGW_ARCH%"-pcre
  - c:\msys64\usr\bin\pacman -Su --noconfirm mingw-w64-"%MINGW_ARCH%"-rust
  - c:\msys64\usr\bin\pacman -Su --noconfirm mingw-w64-"%MINGW_ARCH%"-jansson
  - c:\msys64\usr\bin\pacman -Su --noconfirm mingw-w64-"%MINGW_ARCH%"-nss
  - c:\msys64\usr\bin\pacman -Su --noconfirm mingw-w64-"%MINGW_ARCH%"-nspr

install:
  - choco install winpcap # winpcap userspace
  - if not exist "%PCAP_FILE%" appveyor DownloadFile "%PCAP_URL%" -FileName "%PCAP_FILE%"
  - 7z x -y -o%PCAP_EXTRACT% "%PCAP_FILE%"
  - if "%WINDIVERT%"=="enable" appveyor DownloadFile https://reqrypt.org/download/WinDivert-1.4.3-A.zip -FileName windivert.zip 
  - if "%WINDIVERT%"=="enable" 7z x -y -oc:\ windivert.zip

build_script:
  - set Path=%MINGW_DIR%\bin;c:\msys64\usr\bin;%PCAP_PATH%;%Path%
  - git clone https://github.com/OISF/libhtp -b 0.5.x
  - bash autogen.sh
  - bash configure %CONFIGURE% --disable-shared --%RUST%-rust
  - make -j3
  - ldd src\suricata
  - src\suricata --build-info
  - if "%UNITTESTS%"=="enable" src\suricata -u -l %TEMP% --fatal-unittests

artifacts:
  - path: '*.zip'

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
