# Generated by Django 2.0.7 on 2021-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suricata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suri_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('iface', models.CharField(max_length=12)),
                ('attack_ip', models.CharField(max_length=50)),
                ('victim_ip', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
    ]
